[build]
  base    = "iqra-voice/web"
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html (for React / Vite SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
